server:
  port: 8088

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: kd
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
