server:
  port: 8090

spring:
  application:
    name: api-gateway
  zipkin:
    baseUrl: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka