server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: kd
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


